#define ZFP_TYPE_INT zfp_type_int32
#define DIM_INT_STR 3dInt32
#define ZFP_RATE_PARAM_BITS 19

#define CHECKSUM_ORIGINAL_DATA_BLOCK 0xab8e83e9
#define CHECKSUM_ENCODED_BLOCK 0x57aa1d6b
#define CHECKSUM_ENCODED_PARTIAL_BLOCK 0xfe6953ef

#define CHECKSUM_DECODED_BLOCK 0xdbb57cfa
#define CHECKSUM_DECODED_PARTIAL_BLOCK 0x205d2fad
