#ifndef ZFP_VERSIONING_DEF_UNPREFIXED_CONSTS_H
#define ZFP_VERSIONING_DEF_UNPREFIXED_CONSTS_H

/* constants */
#define ZFP_VERSION_MAJOR ZFP_V5_VERSION_MAJOR
#define ZFP_VERSION_MINOR ZFP_V5_VERSION_MINOR
#define ZFP_VERSION_PATCH ZFP_V5_VERSION_PATCH
#define ZFP_VERSION_RELEASE ZFP_V5_VERSION_RELEASE

#define ZFP_CODEC ZFP_V5_CODEC

#define ZFP_VERSION ZFP_V5_VERSION

#define ZFP_VERSION_STRING ZFP_V5_VERSION_STRING

#define ZFP_MIN_BITS ZFP_V5_MIN_BITS
#define ZFP_MAX_BITS ZFP_V5_MAX_BITS
#define ZFP_MAX_PREC ZFP_V5_MAX_PREC
#define ZFP_MIN_EXP ZFP_V5_MIN_EXP

#define ZFP_HEADER_MAGIC ZFP_V5_HEADER_MAGIC
#define ZFP_HEADER_META ZFP_V5_HEADER_META
#define ZFP_HEADER_MODE ZFP_V5_HEADER_MODE
#define ZFP_HEADER_FULL ZFP_V5_HEADER_FULL

#define ZFP_MAGIC_BITS ZFP_V5_MAGIC_BITS
#define ZFP_META_BITS ZFP_V5_META_BITS
#define ZFP_MODE_SHORT_BITS ZFP_V5_MODE_SHORT_BITS
#define ZFP_MODE_LONG_BITS ZFP_V5_MODE_LONG_BITS
#define ZFP_HEADER_MAX_BITS ZFP_V5_HEADER_MAX_BITS
#define ZFP_MODE_SHORT_MAX ZFP_V5_MODE_SHORT_MAX

#endif
