#undef ZFP_VERSIONING_DEF_UNPREFIXED_CONSTS_H

/* constants */
#undef ZFP_VERSION_MAJOR
#undef ZFP_VERSION_MINOR
#undef ZFP_VERSION_PATCH
#undef ZFP_VERSION_RELEASE

#undef ZFP_CODEC

#undef ZFP_VERSION

#undef ZFP_VERSION_STRING

#undef ZFP_MIN_BITS
#undef ZFP_MAX_BITS
#undef ZFP_MAX_PREC
#undef ZFP_MIN_EXP

#undef ZFP_HEADER_MAGIC
#undef ZFP_HEADER_META
#undef ZFP_HEADER_MODE
#undef ZFP_HEADER_FULL

#undef ZFP_MAGIC_BITS
#undef ZFP_META_BITS
#undef ZFP_MODE_SHORT_BITS
#undef ZFP_MODE_LONG_BITS
#undef ZFP_HEADER_MAX_BITS
#undef ZFP_MODE_SHORT_MAX
