#include "universalConsts.h"

#define FL_PT_DATA
#define ZFP_TYPE zfp_type_float
#define DIM_INT_STR 4dFloat

// single block
#define CHECKSUM_ORIGINAL_DATA_BLOCK 0x8c5867f7
#define CHECKSUM_ENCODED_BLOCK 0x26580b0af77ece38
#define CHECKSUM_ENCODED_PARTIAL_BLOCK 0xb47c6e115d00b400

#define CHECKSUM_DECODED_BLOCK 0x0
#define CHECKSUM_DECODED_PARTIAL_BLOCK 0x0

// entire array
#define CHECKSUM_ORIGINAL_DATA_ARRAY 0x0

#define CHECKSUM_FP_8_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_16_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_32_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_8_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FP_16_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FP_32_DECOMPRESSED_ARRAY 0x0

#define CHECKSUM_FR_8_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_16_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_32_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_8_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FR_16_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FR_32_DECOMPRESSED_ARRAY 0x0

#define CHECKSUM_FA_0p5_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FA_0p25_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FA_0p0625_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FA_0p5_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FA_0p25_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FA_0p0625_DECOMPRESSED_ARRAY 0x0
