#include "universalConsts.h"

#define ZFP_TYPE zfp_type_int64
#define DIM_INT_STR 4dInt64

// single block
#define CHECKSUM_ORIGINAL_DATA_BLOCK 0xc9f0cadc2b040375
#define CHECKSUM_ENCODED_BLOCK 0xbe695ffaef2d6055
#define CHECKSUM_ENCODED_PARTIAL_BLOCK 0x3bf1627a5fd514a7

#define CHECKSUM_DECODED_BLOCK 0x0
#define CHECKSUM_DECODED_PARTIAL_BLOCK 0x0

// entire array
#define CHECKSUM_ORIGINAL_DATA_ARRAY 0x0

#define CHECKSUM_FP_8_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_16_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_32_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_8_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FP_16_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FP_32_DECOMPRESSED_ARRAY 0x0

#define CHECKSUM_FR_8_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_16_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_32_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_8_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FR_16_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FR_32_DECOMPRESSED_ARRAY 0x0
