#include "universalConsts.h"

#define ZFP_TYPE zfp_type_int32
#define DIM_INT_STR 4dInt32

// single block
#define CHECKSUM_ORIGINAL_DATA_BLOCK 0x8b21ff0
#define CHECKSUM_ENCODED_BLOCK 0xf89b3fdf64ff5b5b
#define CHECKSUM_ENCODED_PARTIAL_BLOCK 0x8d094f52b8fd6250

#define CHECKSUM_DECODED_BLOCK 0xcaa8e882
#define CHECKSUM_DECODED_PARTIAL_BLOCK 0x86320cb4

// entire array
#define CHECKSUM_ORIGINAL_DATA_ARRAY 0x0

#define CHECKSUM_FP_8_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_16_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_32_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FP_8_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FP_16_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FP_32_DECOMPRESSED_ARRAY 0x0

#define CHECKSUM_FR_8_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_16_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_32_COMPRESSED_BITSTREAM 0x0
#define CHECKSUM_FR_8_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FR_16_DECOMPRESSED_ARRAY 0x0
#define CHECKSUM_FR_32_DECOMPRESSED_ARRAY 0x0
