name: external
on:
  push:
  pull_request_target:

permissions: write-all

jobs:
  generate_statuses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Kitware/cdash-status@v1.2.1
        with:
          project: ZFP
          github-token: ${{ secrets.CI_GITHUB_ROBOT_TOKEN }}
