name: external
on:
  push:
  pull_request_target:

permissions: write-all

jobs:
  generate_statuses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: Kitware/cdash-status@v2.0.0
        with:
          project: zfp
          github-token: ${{ secrets.CI_GITHUB_ROBOT_TOKEN }}
