name: external
on:
  push:
  pull_request_target:

permissions: write-all

jobs:
  generate_statuses:
    env:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vicentebolea/cdash-status@v1
        project: ZFP
        github-token: ${{ secrets.CI_GITHUB_ROBOT_TOKEN }}
