name: build
on: push
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            cxx_compiler: g++-10
            c_compiler: gcc-10
            omp: ON
            target: all
          
          - os: ubuntu-latest
            cxx_compiler: clang++
            c_compiler: clang
            omp: ON
            target: all            
    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.9.x'
     
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          architecture: x64

      - name: Install ZfPy Dependencies
        run: |
          python -m pip install cython
          python -m pip install oldest-supported-numpy

      - name: Setup Build
        run: |
          mkdir ${{github.workspace}}/build

 
      - name: Run CMake
        id: cmake
        working-directory: ${{github.workspace}}/build
        run: >
          cmake ${{github.workspace}} 
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          -DCMAKE_CXX_COMPILER=${{matrix.cxx_compiler}} 
          -DCMAKE_C_COMPILER=${{matrix.c_compiler}} 
          -DBUILD_TESTING_FULL=ON 
          -DZFP_WITH_OPENMP=${{matrix.omp}} 
          -DOpenMP_C=${{matrix.c_compiler}}
          -DOpenMP_CXX=${{matrix.cxx_compiler}}
          -DOpenMP_C_FLAGS="-fopenmp=libomp -Wno-unused-command-line-argument"
          -DOpenMP_CXX_FLAGS="-fopenmp=libomp -Wno-unused-command-line-argument"
          -DOpenMP_C_LIB_NAMES=libomp
          -DOpenMP_CXX_LIB_NAMES=libomp
          -DOpenMP_libomp_LIBRARY=libomp
          -DBUILD_ZFPY=ON 
          -DPYTHON_INCLUDE_DIR=$(python -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())")
          -DPYTHON_LIBRARY=$(python -c "import distutils.sysconfig as sysconfig; print(sysconfig.get_config_var('LIBDIR'))")
        
      - name: Build
        id: build
        working-directory: ${{github.workspace}}/build
        run: >
          cmake --build . 
          --target ${{matrix.target}} 
          --config ${{env.BUILD_TYPE}}

      - name: Run Tests
        id: test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -VV
